---
"name": "Build Notebooks (push)"
"on":
  "push":
  "workflow_dispatch":
  "schedule":
    - "cron": "0 2 * * *"

permissions:
  contents: read
  packages: write

jobs:
  gen:
    name: Generate job matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
      has_jobs: ${{ steps.gen.outputs.has_jobs }}
    steps:
      - uses: actions/checkout@v4

      - name: Determine targets to build (we want to build everything on push)
        run: |
          set -x
          python3 ci/cached-builds/gen_gha_matrix_jobs.py
        id: gen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

  build:
    needs: ["gen"]
    strategy:
      fail-fast: false
      matrix: "${{ fromJson(needs.gen.outputs.matrix) }}"
    uses: ./.github/workflows/build-notebooks-TEMPLATE.yaml
    if: ${{ fromJson(needs.gen.outputs.has_jobs) }}
    with:
      target: "${{ matrix.target }}"
      github: "${{ toJSON(github) }}"
      subscription: "${{ matrix.subscription }}"
    secrets: inherit
