# This GitHub action is meant to be triggered weekly in order to sync the upstream release branch with the downstream branch fork

name: Sync downstream release branch with upstream's
on:
 # Triggers the workflow every Saturday at 13 pm
 schedule:
   - cron: "0 13 * * 6"

env:
  UPSTREAM_URL: "https://github.com/opendatahub-io/notebooks.git"
  UPSTREAM_BRANCH: "2023a"
  DOWNSTREAM_BRANCH: "2023a"

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:

      - name: Sync release branches (Upstream to Downstream)
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git remote add upstream ${{ env.UPSTREAM_URL }}
          git fetch upstream
          git checkout ${{ env.UPSTREAM_BRANCH }}
          git merge upstream/${{ env.DOWNSTREAM_BRANCH }} -no-edit -m "Merged ${{ env.UPSTREAM_BRANCH }} branch on $(date +%F)"
          git push origin ${{ env.DOWNSTREAM_BRANCH }}

